package generator

import (
	"fmt"
	"strings"

	"github.com/edmand46/arpack/parser"
)

func GenerateCSharp(messages []parser.Message, namespace string) ([]byte, error) {
	return GenerateCSharpSchema(parser.Schema{Messages: messages}, namespace)
}

func GenerateCSharpSchema(schema parser.Schema, namespace string) ([]byte, error) {
	messages := schema.Messages
	var b strings.Builder
	needsLengthGuards := schemaNeedsLengthGuards(messages)
	needsQuantGuards := schemaNeedsQuantRangeGuards(messages)

	b.WriteString("// <auto-generated> arpack </auto-generated>\n")
	b.WriteString("// Code generated by arpack. DO NOT EDIT.\n")
	b.WriteString("#pragma warning disable CS8500\n\n")

	b.WriteString("using System;\n")
	if needsTextEncoding(messages) {
		b.WriteString("using System.Text;\n")
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "namespace %s\n{\n", namespace)

	b.WriteString("    internal static unsafe class ArpackGenerated\n    {\n")
	b.WriteString("        internal static void EnsureReadable(byte* ptr, byte* end, int needed, string context)\n")
	b.WriteString("        {\n")
	b.WriteString("            if (needed < 0 || ptr > end || end - ptr < needed)\n")
	b.WriteString("            {\n")
	b.WriteString("                long available = ptr > end ? 0 : end - ptr;\n")
	b.WriteString("                throw new ArgumentException(\"arpack: buffer too short for \" + context + \": need \" + needed + \" bytes, have \" + available);\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void EnsureWritable(byte* ptr, byte* end, int needed, string context)\n")
	b.WriteString("        {\n")
	b.WriteString("            if (needed < 0 || ptr > end || end - ptr < needed)\n")
	b.WriteString("            {\n")
	b.WriteString("                long available = ptr > end ? 0 : end - ptr;\n")
	b.WriteString("                throw new ArgumentException(\"arpack: buffer too small for \" + context + \": need \" + needed + \" bytes, have \" + available);\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void EnsureFixedArray(Array value, int expectedLength, string context)\n")
	b.WriteString("        {\n")
	b.WriteString("            if (value == null)\n")
	b.WriteString("            {\n")
	b.WriteString("                throw new InvalidOperationException(\"arpack: \" + context + \" is null; expected length \" + expectedLength);\n")
	b.WriteString("            }\n")
	b.WriteString("            if (value.Length != expectedLength)\n")
	b.WriteString("            {\n")
	b.WriteString("                throw new InvalidOperationException(\"arpack: \" + context + \" length mismatch: expected \" + expectedLength + \", got \" + value.Length);\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void WriteU16LE(byte* ptr, ushort value)\n")
	b.WriteString("        {\n")
	b.WriteString("            ptr[0] = (byte)value;\n")
	b.WriteString("            ptr[1] = (byte)(value >> 8);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static ushort ReadU16LE(byte* ptr)\n")
	b.WriteString("        {\n")
	b.WriteString("            return (ushort)(ptr[0] | (ptr[1] << 8));\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void WriteI16LE(byte* ptr, short value)\n")
	b.WriteString("        {\n")
	b.WriteString("            WriteU16LE(ptr, (ushort)value);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static short ReadI16LE(byte* ptr)\n")
	b.WriteString("        {\n")
	b.WriteString("            return (short)ReadU16LE(ptr);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void WriteU32LE(byte* ptr, uint value)\n")
	b.WriteString("        {\n")
	b.WriteString("            ptr[0] = (byte)value;\n")
	b.WriteString("            ptr[1] = (byte)(value >> 8);\n")
	b.WriteString("            ptr[2] = (byte)(value >> 16);\n")
	b.WriteString("            ptr[3] = (byte)(value >> 24);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static uint ReadU32LE(byte* ptr)\n")
	b.WriteString("        {\n")
	b.WriteString("            return (uint)(ptr[0] | (ptr[1] << 8) | (ptr[2] << 16) | (ptr[3] << 24));\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void WriteI32LE(byte* ptr, int value)\n")
	b.WriteString("        {\n")
	b.WriteString("            WriteU32LE(ptr, (uint)value);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static int ReadI32LE(byte* ptr)\n")
	b.WriteString("        {\n")
	b.WriteString("            return (int)ReadU32LE(ptr);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void WriteU64LE(byte* ptr, ulong value)\n")
	b.WriteString("        {\n")
	b.WriteString("            ptr[0] = (byte)value;\n")
	b.WriteString("            ptr[1] = (byte)(value >> 8);\n")
	b.WriteString("            ptr[2] = (byte)(value >> 16);\n")
	b.WriteString("            ptr[3] = (byte)(value >> 24);\n")
	b.WriteString("            ptr[4] = (byte)(value >> 32);\n")
	b.WriteString("            ptr[5] = (byte)(value >> 40);\n")
	b.WriteString("            ptr[6] = (byte)(value >> 48);\n")
	b.WriteString("            ptr[7] = (byte)(value >> 56);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static ulong ReadU64LE(byte* ptr)\n")
	b.WriteString("        {\n")
	b.WriteString("            return (ulong)ptr[0] |\n")
	b.WriteString("                ((ulong)ptr[1] << 8) |\n")
	b.WriteString("                ((ulong)ptr[2] << 16) |\n")
	b.WriteString("                ((ulong)ptr[3] << 24) |\n")
	b.WriteString("                ((ulong)ptr[4] << 32) |\n")
	b.WriteString("                ((ulong)ptr[5] << 40) |\n")
	b.WriteString("                ((ulong)ptr[6] << 48) |\n")
	b.WriteString("                ((ulong)ptr[7] << 56);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void WriteI64LE(byte* ptr, long value)\n")
	b.WriteString("        {\n")
	b.WriteString("            WriteU64LE(ptr, (ulong)value);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static long ReadI64LE(byte* ptr)\n")
	b.WriteString("        {\n")
	b.WriteString("            return (long)ReadU64LE(ptr);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static uint Float32ToBits(float value)\n")
	b.WriteString("        {\n")
	b.WriteString("            return *(uint*)&value;\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static float BitsToFloat32(uint value)\n")
	b.WriteString("        {\n")
	b.WriteString("            return *(float*)&value;\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static ulong Float64ToBits(double value)\n")
	b.WriteString("        {\n")
	b.WriteString("            return *(ulong*)&value;\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static double BitsToFloat64(ulong value)\n")
	b.WriteString("        {\n")
	b.WriteString("            return *(double*)&value;\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void WriteFloat32LE(byte* ptr, float value)\n")
	b.WriteString("        {\n")
	b.WriteString("            WriteU32LE(ptr, Float32ToBits(value));\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static float ReadFloat32LE(byte* ptr)\n")
	b.WriteString("        {\n")
	b.WriteString("            return BitsToFloat32(ReadU32LE(ptr));\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static void WriteFloat64LE(byte* ptr, double value)\n")
	b.WriteString("        {\n")
	b.WriteString("            WriteU64LE(ptr, Float64ToBits(value));\n")
	b.WriteString("        }\n\n")
	b.WriteString("        internal static double ReadFloat64LE(byte* ptr)\n")
	b.WriteString("        {\n")
	b.WriteString("            return BitsToFloat64(ReadU64LE(ptr));\n")
	b.WriteString("        }\n\n")
	if needsLengthGuards {
		b.WriteString("        internal static ushort EnsureU16Length(int length, string context)\n")
		b.WriteString("        {\n")
		b.WriteString("            if (length > 65535)\n")
		b.WriteString("            {\n")
		b.WriteString("                throw new InvalidOperationException(\"arpack: \" + context + \" exceeds uint16 limit\");\n")
		b.WriteString("            }\n")
		b.WriteString("            return (ushort)length;\n")
		b.WriteString("        }\n\n")
	}
	if needsQuantGuards {
		b.WriteString("        internal static void EnsureQuantizedRange(double value, double min, double max, string context)\n")
		b.WriteString("        {\n")
		b.WriteString("            if (double.IsNaN(value) || value < min || value > max)\n")
		b.WriteString("            {\n")
		b.WriteString("                throw new ArgumentOutOfRangeException(context, \"arpack: quantized value out of range for \" + context);\n")
		b.WriteString("            }\n")
		b.WriteString("        }\n")
	}
	b.WriteString("    }\n\n")

	enumNames := make(map[string]struct{}, len(schema.Enums))
	for _, enum := range schema.Enums {
		enumNames[enum.Name] = struct{}{}
	}

	for _, enum := range schema.Enums {
		writeCSharpEnum(&b, enum)
		b.WriteString("\n")
	}

	for i, msg := range messages {
		if err := writeCSharpMessage(&b, msg, enumNames); err != nil {
			return nil, fmt.Errorf("message %s: %w", msg.Name, err)
		}
		if i < len(messages)-1 {
			b.WriteString("\n")
		}
	}

	b.WriteString("}\n")
	return []byte(b.String()), nil
}

func writeCSharpEnum(b *strings.Builder, enum parser.Enum) {
	fmt.Fprintf(b, "    public enum %s : %s\n    {\n", enum.Name, csharpEnumBaseType(enum))
	for i, value := range enum.Values {
		fmt.Fprintf(b, "        %s = %s", csharpEnumValueName(enum.Name, value.Name), value.Value)
		if i < len(enum.Values)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("    }\n")
}

func writeCSharpMessage(b *strings.Builder, msg parser.Message, enumNames map[string]struct{}) error {
	segs := segmentFields(msg.Fields)

	b.WriteString("    public unsafe struct ")
	b.WriteString(msg.Name)
	b.WriteString("\n    {\n")

	for _, f := range msg.Fields {
		fmt.Fprintf(b, "        public %s %s;\n", csharpTypeName(f, enumNames), f.Name)
	}
	b.WriteString("\n")

	b.WriteString("        public int Serialize(Span<byte> buffer)\n")
	b.WriteString("        {\n")
	b.WriteString("            fixed (byte* ptr = buffer)\n")
	b.WriteString("            {\n")
	b.WriteString("                return Serialize(ptr, buffer.Length);\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")

	b.WriteString("        public int Serialize(byte* buffer, int length)\n")
	b.WriteString("        {\n")
	b.WriteString("            byte* ptr = buffer;\n")
	b.WriteString("            byte* end = buffer + length;\n")
	for i, seg := range segs {
		if seg.single != nil {
			if err := writeCSharpSerializeField(b, *seg.single, "            ", enumNames); err != nil {
				return err
			}
		} else {
			writeCSharpBoolGroupSerialize(b, seg.bools, i, "            ")
		}
	}
	b.WriteString("            return (int)(ptr - buffer);\n")
	b.WriteString("        }\n\n")

	fmt.Fprintf(b, "        public static int Deserialize(ReadOnlySpan<byte> data, out %s msg)\n", msg.Name)
	b.WriteString("        {\n")
	b.WriteString("            fixed (byte* ptr = data)\n")
	b.WriteString("            {\n")
	fmt.Fprintf(b, "                return Deserialize(ptr, data.Length, out msg);\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")

	fmt.Fprintf(b, "        public static int Deserialize(byte* buffer, int length, out %s msg)\n", msg.Name)
	b.WriteString("        {\n")
	b.WriteString("            byte* ptr = buffer;\n")
	b.WriteString("            byte* end = buffer + length;\n")
	b.WriteString("            msg = default;\n")
	for i, seg := range segs {
		if seg.single != nil {
			if err := writeCSharpDeserializeField(b, "msg", *seg.single, "            ", enumNames); err != nil {
				return err
			}
		} else {
			writeCSharpBoolGroupDeserialize(b, "msg", seg.bools, i, "            ")
		}
	}
	b.WriteString("            return (int)(ptr - buffer);\n")
	b.WriteString("        }\n")

	b.WriteString("    }\n")
	return nil
}

func writeCSharpBoolGroupSerialize(b *strings.Builder, bools []parser.Field, groupIdx int, indent string) {
	varName := fmt.Sprintf("_boolByte%d", groupIdx)
	fmt.Fprintf(b, "%sbyte %s = 0;\n", indent, varName)
	for bit, f := range bools {
		fmt.Fprintf(b, "%sif (%s) %s |= (byte)(1 << %d);\n", indent, f.Name, varName, bit)
	}
	fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 1, %q);\n", indent, "bool group")
	fmt.Fprintf(b, "%s*ptr = %s; ptr++;\n", indent, varName)
}

func writeCSharpBoolGroupDeserialize(b *strings.Builder, recv string, bools []parser.Field, groupIdx int, indent string) {
	varName := fmt.Sprintf("_boolByte%d", groupIdx)
	fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 1, %q);\n", indent, "bool group")
	fmt.Fprintf(b, "%sbyte %s = *ptr; ptr++;\n", indent, varName)
	for bit, f := range bools {
		fmt.Fprintf(b, "%s%s.%s = (%s & (1 << %d)) != 0;\n", indent, recv, f.Name, varName, bit)
	}
}

func writeCSharpSerializeField(b *strings.Builder, f parser.Field, indent string, enumNames map[string]struct{}) error {
	switch f.Kind {
	case parser.KindPrimitive:
		return writeCSharpSerializePrimitive(b, f.Name, f, indent, enumNames)
	case parser.KindNested:
		fmt.Fprintf(b, "%sptr += %s.Serialize(ptr, (int)(end - ptr));\n", indent, f.Name)
	case parser.KindFixedArray:
		iVar := "_i" + f.Name
		fmt.Fprintf(b, "%sArpackGenerated.EnsureFixedArray(%s, %d, %q);\n", indent, f.Name, f.FixedLen, "fixed array for "+f.Name)
		fmt.Fprintf(b, "%sfor (int %s = 0; %s < %d; %s++)\n%s{\n",
			indent, iVar, iVar, f.FixedLen, iVar, indent)
		elemField := parser.Field{
			Name:      f.Name + "[" + iVar + "]",
			Kind:      f.Elem.Kind,
			Primitive: f.Elem.Primitive,
			NamedType: f.Elem.NamedType,
			Quant:     f.Elem.Quant,
			TypeName:  f.Elem.TypeName,
			Elem:      f.Elem.Elem,
			FixedLen:  f.Elem.FixedLen,
		}
		if err := writeCSharpSerializeField(b, elemField, indent+"    ", enumNames); err != nil {
			return err
		}
		fmt.Fprintf(b, "%s}\n", indent)
	case parser.KindSlice:
		lenVar := "_len" + sanitizeVarName(f.Name)
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 2, %q);\n", indent, "slice length for "+f.Name)
		fmt.Fprintf(b, "%sushort %s = ArpackGenerated.EnsureU16Length(%s?.Length ?? 0, %q); ArpackGenerated.WriteU16LE(ptr, %s); ptr += 2;\n",
			indent, lenVar, f.Name, lengthContext(f), lenVar)
		fmt.Fprintf(b, "%sif (%s != null)\n%s{\n", indent, f.Name, indent)
		iVar := "_i" + f.Name
		fmt.Fprintf(b, "%s    for (int %s = 0; %s < %s.Length; %s++)\n%s    {\n",
			indent, iVar, iVar, f.Name, iVar, indent)
		elemField := parser.Field{
			Name:      f.Name + "[" + iVar + "]",
			Kind:      f.Elem.Kind,
			Primitive: f.Elem.Primitive,
			NamedType: f.Elem.NamedType,
			Quant:     f.Elem.Quant,
			TypeName:  f.Elem.TypeName,
			Elem:      f.Elem.Elem,
			FixedLen:  f.Elem.FixedLen,
		}
		if err := writeCSharpSerializeField(b, elemField, indent+"        ", enumNames); err != nil {
			return err
		}
		fmt.Fprintf(b, "%s    }\n%s}\n", indent, indent)
	}
	return nil
}

func writeCSharpSerializePrimitive(
	b *strings.Builder,
	access string,
	f parser.Field,
	indent string,
	enumNames map[string]struct{},
) error {
	if f.Quant != nil {
		return writeCSharpSerializeQuant(b, access, f, indent)
	}
	valueExpr := csharpSerializeValueExpr(access, f, enumNames)
	switch f.Primitive {
	case parser.KindFloat32:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 4, %q);\n", indent, "float32")
		fmt.Fprintf(b, "%sArpackGenerated.WriteFloat32LE(ptr, %s); ptr += 4;\n", indent, valueExpr)
	case parser.KindFloat64:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 8, %q);\n", indent, "float64")
		fmt.Fprintf(b, "%sArpackGenerated.WriteFloat64LE(ptr, %s); ptr += 8;\n", indent, valueExpr)
	case parser.KindInt8:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 1, %q);\n", indent, "int8")
		fmt.Fprintf(b, "%s*(sbyte*)ptr = %s; ptr += 1;\n", indent, valueExpr)
	case parser.KindUint8:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 1, %q);\n", indent, "uint8")
		fmt.Fprintf(b, "%s*ptr = %s; ptr += 1;\n", indent, valueExpr)
	case parser.KindBool:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 1, %q);\n", indent, "bool")
		fmt.Fprintf(b, "%s*ptr = (byte)(%s ? 1 : 0); ptr += 1;\n", indent, valueExpr)
	case parser.KindInt16:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 2, %q);\n", indent, "int16")
		fmt.Fprintf(b, "%sArpackGenerated.WriteI16LE(ptr, %s); ptr += 2;\n", indent, valueExpr)
	case parser.KindUint16:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 2, %q);\n", indent, "uint16")
		fmt.Fprintf(b, "%sArpackGenerated.WriteU16LE(ptr, %s); ptr += 2;\n", indent, valueExpr)
	case parser.KindInt32:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 4, %q);\n", indent, "int32")
		fmt.Fprintf(b, "%sArpackGenerated.WriteI32LE(ptr, %s); ptr += 4;\n", indent, valueExpr)
	case parser.KindUint32:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 4, %q);\n", indent, "uint32")
		fmt.Fprintf(b, "%sArpackGenerated.WriteU32LE(ptr, %s); ptr += 4;\n", indent, valueExpr)
	case parser.KindInt64:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 8, %q);\n", indent, "int64")
		fmt.Fprintf(b, "%sArpackGenerated.WriteI64LE(ptr, %s); ptr += 8;\n", indent, valueExpr)
	case parser.KindUint64:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 8, %q);\n", indent, "uint64")
		fmt.Fprintf(b, "%sArpackGenerated.WriteU64LE(ptr, %s); ptr += 8;\n", indent, valueExpr)
	case parser.KindString:
		lenVar := "_slen" + sanitizeVarName(access)
		fmt.Fprintf(b, "%sint %s = %s != null ? Encoding.UTF8.GetByteCount(%s) : 0;\n",
			indent, lenVar, valueExpr, valueExpr)
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 2, %q);\n", indent, "string length for "+f.Name)
		fmt.Fprintf(b, "%sArpackGenerated.WriteU16LE(ptr, ArpackGenerated.EnsureU16Length(%s, %q)); ptr += 2;\n",
			indent, lenVar, lengthContext(f))
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, %s, %q);\n", indent, lenVar, "string data for "+f.Name)
		fmt.Fprintf(b, "%sif (%s != null && %s > 0)\n%s{\n", indent, valueExpr, lenVar, indent)
		fmt.Fprintf(b, "%s    fixed (char* _chars%s = %s)\n%s    {\n",
			indent, sanitizeVarName(access), valueExpr, indent)
		fmt.Fprintf(b, "%s        Encoding.UTF8.GetBytes(_chars%s, %s.Length, ptr, %s);\n",
			indent, sanitizeVarName(access), valueExpr, lenVar)
		fmt.Fprintf(b, "%s    }\n", indent)
		fmt.Fprintf(b, "%s}\n", indent)
		fmt.Fprintf(b, "%sptr += %s;\n", indent, lenVar)
	}
	return nil
}

func writeCSharpSerializeQuant(b *strings.Builder, access string, f parser.Field, indent string) error {
	q := f.Quant
	fmt.Fprintf(b, "%sArpackGenerated.EnsureQuantizedRange(%s, %g, %g, %q);\n",
		indent, access, q.Min, q.Max, quantContext(f))
	if q.Bits == 8 {
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 1, %q);\n", indent, "quantized value for "+f.Name)
		fmt.Fprintf(b, "%s*ptr = %s; ptr += 1;\n", indent, quantizeExpr("cs", access, q, 8))
	} else {
		fmt.Fprintf(b, "%sArpackGenerated.EnsureWritable(ptr, end, 2, %q);\n", indent, "quantized value for "+f.Name)
		fmt.Fprintf(b, "%sArpackGenerated.WriteU16LE(ptr, %s); ptr += 2;\n", indent, quantizeExpr("cs", access, q, 16))
	}
	return nil
}

func writeCSharpDeserializeField(
	b *strings.Builder,
	recv string,
	f parser.Field,
	indent string,
	enumNames map[string]struct{},
) error {
	access := recv + "." + f.Name
	switch f.Kind {
	case parser.KindPrimitive:
		return writeCSharpDeserializePrimitive(b, access, f, indent, enumNames)
	case parser.KindNested:
		fmt.Fprintf(b, "%sint _n%s = %s.Deserialize(ptr, (int)(end - ptr), out %s);\n", indent, sanitizeVarName(f.Name), f.TypeName, access)
		fmt.Fprintf(b, "%sptr += _n%s;\n", indent, sanitizeVarName(f.Name))
	case parser.KindFixedArray:
		iVar := "_i" + f.Name
		fmt.Fprintf(b, "%s%s = new %s[%d];\n", indent, access, csharpTypeName(*f.Elem, enumNames), f.FixedLen)
		fmt.Fprintf(b, "%sfor (int %s = 0; %s < %d; %s++)\n%s{\n",
			indent, iVar, iVar, f.FixedLen, iVar, indent)
		elemField := parser.Field{
			Name:      f.Name + "[" + iVar + "]",
			Kind:      f.Elem.Kind,
			Primitive: f.Elem.Primitive,
			NamedType: f.Elem.NamedType,
			Quant:     f.Elem.Quant,
			TypeName:  f.Elem.TypeName,
			Elem:      f.Elem.Elem,
			FixedLen:  f.Elem.FixedLen,
		}
		if err := writeCSharpDeserializeField(b, recv, elemField, indent+"    ", enumNames); err != nil {
			return err
		}
		fmt.Fprintf(b, "%s}\n", indent)
	case parser.KindSlice:
		lenVar := "_len" + sanitizeVarName(f.Name)
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 2, %q);\n", indent, "slice length for "+f.Name)
		fmt.Fprintf(b, "%sint %s = ArpackGenerated.ReadU16LE(ptr); ptr += 2;\n", indent, lenVar)
		fmt.Fprintf(b, "%s%s = new %s[%s];\n", indent, access, csharpTypeName(*f.Elem, enumNames), lenVar)
		iVar := "_i" + sanitizeVarName(f.Name)
		fmt.Fprintf(b, "%sfor (int %s = 0; %s < %s; %s++)\n%s{\n",
			indent, iVar, iVar, lenVar, iVar, indent)
		elemField := parser.Field{
			Name:      f.Name + "[" + iVar + "]",
			Kind:      f.Elem.Kind,
			Primitive: f.Elem.Primitive,
			NamedType: f.Elem.NamedType,
			Quant:     f.Elem.Quant,
			TypeName:  f.Elem.TypeName,
			Elem:      f.Elem.Elem,
			FixedLen:  f.Elem.FixedLen,
		}
		if err := writeCSharpDeserializeField(b, recv, elemField, indent+"    ", enumNames); err != nil {
			return err
		}
		fmt.Fprintf(b, "%s}\n", indent)
	}
	return nil
}

func writeCSharpDeserializePrimitive(
	b *strings.Builder,
	access string,
	f parser.Field,
	indent string,
	enumNames map[string]struct{},
) error {
	if f.Quant != nil {
		return writeCSharpDeserializeQuant(b, access, f, indent)
	}
	switch f.Primitive {
	case parser.KindFloat32:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 4, %q);\n", indent, "float32")
		fmt.Fprintf(b, "%s%s = %s; ptr += 4;\n", indent, access, csharpDeserializeValueExpr("ArpackGenerated.ReadFloat32LE(ptr)", f, enumNames))
	case parser.KindFloat64:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 8, %q);\n", indent, "float64")
		fmt.Fprintf(b, "%s%s = %s; ptr += 8;\n", indent, access, csharpDeserializeValueExpr("ArpackGenerated.ReadFloat64LE(ptr)", f, enumNames))
	case parser.KindInt8:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 1, %q);\n", indent, "int8")
		fmt.Fprintf(b, "%s%s = %s; ptr += 1;\n", indent, access, csharpDeserializeValueExpr("*(sbyte*)ptr", f, enumNames))
	case parser.KindUint8:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 1, %q);\n", indent, "uint8")
		fmt.Fprintf(b, "%s%s = %s; ptr += 1;\n", indent, access, csharpDeserializeValueExpr("*ptr", f, enumNames))
	case parser.KindBool:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 1, %q);\n", indent, "bool")
		fmt.Fprintf(b, "%s%s = %s; ptr += 1;\n", indent, access, csharpDeserializeValueExpr("*ptr != 0", f, enumNames))
	case parser.KindInt16:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 2, %q);\n", indent, "int16")
		fmt.Fprintf(b, "%s%s = %s; ptr += 2;\n", indent, access, csharpDeserializeValueExpr("ArpackGenerated.ReadI16LE(ptr)", f, enumNames))
	case parser.KindUint16:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 2, %q);\n", indent, "uint16")
		fmt.Fprintf(b, "%s%s = %s; ptr += 2;\n", indent, access, csharpDeserializeValueExpr("ArpackGenerated.ReadU16LE(ptr)", f, enumNames))
	case parser.KindInt32:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 4, %q);\n", indent, "int32")
		fmt.Fprintf(b, "%s%s = %s; ptr += 4;\n", indent, access, csharpDeserializeValueExpr("ArpackGenerated.ReadI32LE(ptr)", f, enumNames))
	case parser.KindUint32:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 4, %q);\n", indent, "uint32")
		fmt.Fprintf(b, "%s%s = %s; ptr += 4;\n", indent, access, csharpDeserializeValueExpr("ArpackGenerated.ReadU32LE(ptr)", f, enumNames))
	case parser.KindInt64:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 8, %q);\n", indent, "int64")
		fmt.Fprintf(b, "%s%s = %s; ptr += 8;\n", indent, access, csharpDeserializeValueExpr("ArpackGenerated.ReadI64LE(ptr)", f, enumNames))
	case parser.KindUint64:
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 8, %q);\n", indent, "uint64")
		fmt.Fprintf(b, "%s%s = %s; ptr += 8;\n", indent, access, csharpDeserializeValueExpr("ArpackGenerated.ReadU64LE(ptr)", f, enumNames))
	case parser.KindString:
		lenVar := "_slen" + sanitizeVarName(access)
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 2, %q);\n", indent, "string length for "+f.Name)
		fmt.Fprintf(b, "%sint %s = ArpackGenerated.ReadU16LE(ptr); ptr += 2;\n", indent, lenVar)
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, %s, %q);\n", indent, lenVar, "string data for "+f.Name)
		expr := fmt.Sprintf("%s > 0 ? Encoding.UTF8.GetString(ptr, %s) : string.Empty", lenVar, lenVar)
		fmt.Fprintf(b, "%s%s = %s;\n", indent, access, csharpDeserializeValueExpr(expr, f, enumNames))
		fmt.Fprintf(b, "%sptr += %s;\n", indent, lenVar)
	}
	return nil
}

func writeCSharpDeserializeQuant(b *strings.Builder, access string, f parser.Field, indent string) error {
	q := f.Quant
	if q.Bits == 8 {
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 1, %q);\n", indent, "quantized value for "+f.Name)
		expr := dequantizeExpr("cs", "*ptr", q, f.Primitive)
		fmt.Fprintf(b, "%s%s = %s; ptr += 1;\n", indent, access, csharpDeserializeValueExpr(expr, f, nil))
	} else {
		fmt.Fprintf(b, "%sArpackGenerated.EnsureReadable(ptr, end, 2, %q);\n", indent, "quantized value for "+f.Name)
		expr := dequantizeExpr("cs", "ArpackGenerated.ReadU16LE(ptr)", q, f.Primitive)
		fmt.Fprintf(b, "%s%s = %s; ptr += 2;\n", indent, access, csharpDeserializeValueExpr(expr, f, nil))
	}
	return nil
}
func needsTextEncoding(messages []parser.Message) bool {
	for _, msg := range messages {
		for _, f := range msg.Fields {
			if fieldNeedsEncoding(f) {
				return true
			}
		}
	}
	return false
}

func fieldNeedsEncoding(f parser.Field) bool {
	switch f.Kind {
	case parser.KindPrimitive:
		return f.Primitive == parser.KindString
	case parser.KindFixedArray, parser.KindSlice:
		if f.Elem != nil {
			return fieldNeedsEncoding(*f.Elem)
		}
	}
	return false
}

func csharpTypeName(f parser.Field, enumNames map[string]struct{}) string {
	switch f.Kind {
	case parser.KindPrimitive:
		if csharpIsEnumType(f, enumNames) {
			return f.NamedType
		}
		return f.CSharpPrimitiveTypeName()
	case parser.KindNested:
		return f.TypeName
	case parser.KindFixedArray:
		return csharpTypeName(*f.Elem, enumNames) + "[]"
	case parser.KindSlice:
		return csharpTypeName(*f.Elem, enumNames) + "[]"
	}
	return "unknown"
}

func csharpSerializeValueExpr(access string, f parser.Field, enumNames map[string]struct{}) string {
	if !csharpIsEnumType(f, enumNames) {
		return access
	}
	return "(" + f.CSharpPrimitiveTypeName() + ")" + access
}

func csharpDeserializeValueExpr(expr string, f parser.Field, enumNames map[string]struct{}) string {
	if !csharpIsEnumType(f, enumNames) {
		return expr
	}
	return "(" + f.NamedType + ")(" + expr + ")"
}

func csharpIsEnumType(f parser.Field, enumNames map[string]struct{}) bool {
	if f.NamedType == "" {
		return false
	}
	_, ok := enumNames[f.NamedType]
	return ok
}

func csharpEnumBaseType(enum parser.Enum) string {
	field := parser.Field{Primitive: enum.Primitive}
	return field.CSharpPrimitiveTypeName()
}

func csharpEnumValueName(enumName, valueName string) string {
	return valueName
}
