package generator

import (
	"fmt"
	"strings"

	"github.com/edmand46/arpack/parser"
)

func GenerateGML(messages []parser.Message) ([]byte, error) {
	return GenerateGMLSchema(parser.Schema{Messages: messages})
}

func GenerateGMLSchema(schema parser.Schema) ([]byte, error) {
	messages := schema.Messages
	var b strings.Builder

	b.WriteString("// <auto-generated> arpack </auto-generated>\n")
	b.WriteString("// Code generated by arpack. DO NOT EDIT.\n\n")

	enumNames := make(map[string]struct{}, len(schema.Enums))
	for _, enum := range schema.Enums {
		if enum.Primitive == parser.KindInt64 || enum.Primitive == parser.KindUint64 {
			return nil, fmt.Errorf("gml target does not support int64/uint64 enum %s: GML enums are number-based and cannot represent big integer values", enum.Name)
		}
		enumNames[enum.Name] = struct{}{}
	}

	if len(messages) > 0 {
		needsLengthGuards := schemaNeedsLengthGuards(messages)
		needsQuantGuards := schemaNeedsQuantRangeGuards(messages)
		writeGMLHelpers(&b, needsLengthGuards, needsQuantGuards)
	}

	for _, enum := range schema.Enums {
		writeGMLEnum(&b, enum)
		b.WriteString("\n")
	}

	for _, msg := range messages {
		if err := writeGMLConstructor(&b, msg, enumNames); err != nil {
			return nil, fmt.Errorf("message %s: %w", msg.Name, err)
		}
		b.WriteString("\n")
	}

	for _, msg := range messages {
		if err := writeGMLDeserializer(&b, msg); err != nil {
			return nil, fmt.Errorf("message %s: %w", msg.Name, err)
		}
		b.WriteString("\n")
	}

	return []byte(b.String()), nil
}

func writeGMLHelpers(b *strings.Builder, needsLengthGuards, needsQuantGuards bool) {
	b.WriteString("function arpack_ensure_readable(_buf, _needed, _context)\n")
	b.WriteString("{\n")
	b.WriteString("    var _pos = buffer_tell(_buf);\n")
	b.WriteString("    var _size = buffer_get_size(_buf);\n")
	b.WriteString("    if (_pos + _needed > _size)\n")
	b.WriteString("    {\n")
	b.WriteString("        show_error(\"arpack: buffer too short for \" + _context + \": need \" + string(_needed) + \" bytes, have \" + string(_size - _pos), true);\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	if needsLengthGuards {
		b.WriteString("function arpack_ensure_u16_length(_length, _context)\n")
		b.WriteString("{\n")
		b.WriteString("    if (_length > 65535)\n")
		b.WriteString("    {\n")
		b.WriteString("        show_error(\"arpack: \" + _context + \" exceeds uint16 limit\", true);\n")
		b.WriteString("    }\n")
		b.WriteString("    return _length;\n")
		b.WriteString("}\n\n")
	}

	if needsQuantGuards {
		b.WriteString("function arpack_ensure_quant_range(_value, _min, _max, _context)\n")
		b.WriteString("{\n")
		b.WriteString("    if (_value != _value || _value < _min || _value > _max)\n")
		b.WriteString("    {\n")
		b.WriteString("        show_error(\"arpack: quantized value out of range for \" + _context, true);\n")
		b.WriteString("    }\n")
		b.WriteString("    return _value;\n")
		b.WriteString("}\n\n")
	}
}

func writeGMLEnum(b *strings.Builder, enum parser.Enum) {
	fmt.Fprintf(b, "enum %s\n", enum.Name)
	b.WriteString("{\n")
	for i, value := range enum.Values {
		fmt.Fprintf(b, "    %s = %s", value.Name, value.Value)
		if i < len(enum.Values)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("}\n")
}

func writeGMLConstructor(b *strings.Builder, msg parser.Message, enumNames map[string]struct{}) error {
	segs := segmentFields(msg.Fields)

	fmt.Fprintf(b, "function %s() constructor\n", msg.Name)
	b.WriteString("{\n")
	for _, f := range msg.Fields {
		writeGMLDefault(b, "self", f, enumNames, "    ")
	}
	b.WriteString("\n")
	b.WriteString("    static serialize = function(_buf)\n")
	b.WriteString("    {\n")
	b.WriteString("        var _owns = false;\n")
	b.WriteString("        if (is_undefined(_buf))\n")
	b.WriteString("        {\n")
	b.WriteString("            _buf = buffer_create(128, buffer_grow, 1);\n")
	b.WriteString("            _owns = true;\n")
	b.WriteString("        }\n")
	for i, seg := range segs {
		if seg.single != nil {
			if err := writeGMLSerializeField(b, "self", *seg.single, "        "); err != nil {
				return err
			}
		} else {
			writeGMLBoolGroupSerialize(b, "self", seg.bools, i, "        ")
		}
	}
	b.WriteString("        if (_owns)\n")
	b.WriteString("        {\n")
	b.WriteString("            buffer_resize(_buf, buffer_tell(_buf));\n")
	b.WriteString("            buffer_seek(_buf, buffer_seek_start, 0);\n")
	b.WriteString("        }\n")
	b.WriteString("        return _buf;\n")
	b.WriteString("    };\n")
	b.WriteString("}\n")
	return nil
}

func writeGMLDeserializer(b *strings.Builder, msg parser.Message) error {
	segs := segmentFields(msg.Fields)

	fmt.Fprintf(b, "%s.deserialize = function(_buf)\n", msg.Name)
	b.WriteString("{\n")
	b.WriteString("    var _start = buffer_tell(_buf);\n")
	fmt.Fprintf(b, "    var _msg = new %s();\n", msg.Name)
	for i, seg := range segs {
		if seg.single != nil {
			if err := writeGMLDeserializeField(b, "_msg", *seg.single, "    "); err != nil {
				return err
			}
		} else {
			writeGMLBoolGroupDeserialize(b, "_msg", seg.bools, i, "    ")
		}
	}
	b.WriteString("    return [_msg, buffer_tell(_buf) - _start];\n")
	b.WriteString("};\n")
	return nil
}

func writeGMLDefault(b *strings.Builder, recv string, f parser.Field, enumNames map[string]struct{}, indent string) {
	access := gmlFieldAccess(recv, f.Name)
	if f.Kind != parser.KindFixedArray {
		fmt.Fprintf(b, "%s%s = %s;\n", indent, access, gmlDefaultValue(f, enumNames))
		return
	}

	if !gmlDefaultNeedsFactory(*f.Elem) {
		fmt.Fprintf(b, "%s%s = array_create(%d, %s);\n", indent, access, f.FixedLen, gmlDefaultValue(*f.Elem, enumNames))
		return
	}

	iVar := gmlLoopVar(f)
	fmt.Fprintf(b, "%s%s = array_create(0);\n", indent, access)
	fmt.Fprintf(b, "%sfor (var %s = 0; %s < %d; %s++)\n", indent, iVar, iVar, f.FixedLen, iVar)
	fmt.Fprintf(b, "%s{\n", indent)
	elemField := *f.Elem
	elemField.Name = f.Name + "[" + iVar + "]"
	writeGMLDefault(b, recv, elemField, enumNames, indent+"    ")
	fmt.Fprintf(b, "%s}\n", indent)
}

func writeGMLBoolGroupSerialize(b *strings.Builder, recv string, bools []parser.Field, groupIdx int, indent string) {
	varName := fmt.Sprintf("_bool_byte_%d", groupIdx)
	fmt.Fprintf(b, "%svar %s = 0;\n", indent, varName)
	for bit, f := range bools {
		fmt.Fprintf(b, "%sif (%s) %s |= 1 << %d;\n", indent, gmlFieldAccess(recv, f.Name), varName, bit)
	}
	fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u8, %s);\n", indent, varName)
}

func writeGMLBoolGroupDeserialize(b *strings.Builder, recv string, bools []parser.Field, groupIdx int, indent string) {
	varName := fmt.Sprintf("_bool_byte_%d", groupIdx)
	fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 1, %q);\n", indent, "bool group")
	fmt.Fprintf(b, "%svar %s = buffer_read(_buf, buffer_u8);\n", indent, varName)
	for bit, f := range bools {
		fmt.Fprintf(b, "%s%s = (%s & (1 << %d)) != 0;\n", indent, gmlFieldAccess(recv, f.Name), varName, bit)
	}
}

func writeGMLSerializeField(b *strings.Builder, recv string, f parser.Field, indent string) error {
	access := gmlFieldAccess(recv, f.Name)
	switch f.Kind {
	case parser.KindPrimitive:
		return writeGMLSerializePrimitive(b, access, f, indent)
	case parser.KindNested:
		fmt.Fprintf(b, "%s%s.serialize(_buf);\n", indent, access)
	case parser.KindFixedArray:
		fmt.Fprintf(b, "%sif (array_length(%s) != %d) show_error(\"arpack: fixed array for %s length mismatch: expected %d, got \" + string(array_length(%s)), true);\n",
			indent, access, f.FixedLen, f.Name, f.FixedLen, access)
		iVar := gmlLoopVar(f)
		fmt.Fprintf(b, "%sfor (var %s = 0; %s < %d; %s++)\n", indent, iVar, iVar, f.FixedLen, iVar)
		fmt.Fprintf(b, "%s{\n", indent)
		elemField := *f.Elem
		elemField.Name = f.Name + "[" + iVar + "]"
		if err := writeGMLSerializeField(b, recv, elemField, indent+"    "); err != nil {
			return err
		}
		fmt.Fprintf(b, "%s}\n", indent)
	case parser.KindSlice:
		lenVar := gmlLenVar(f)
		fmt.Fprintf(b, "%svar %s = array_length(%s);\n", indent, lenVar, access)
		fmt.Fprintf(b, "%s%s = arpack_ensure_u16_length(%s, %q);\n", indent, lenVar, lenVar, lengthContext(f))
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u16, %s);\n", indent, lenVar)
		iVar := gmlLoopVar(f)
		fmt.Fprintf(b, "%sfor (var %s = 0; %s < %s; %s++)\n", indent, iVar, iVar, lenVar, iVar)
		fmt.Fprintf(b, "%s{\n", indent)
		elemField := *f.Elem
		elemField.Name = f.Name + "[" + iVar + "]"
		if err := writeGMLSerializeField(b, recv, elemField, indent+"    "); err != nil {
			return err
		}
		fmt.Fprintf(b, "%s}\n", indent)
	}
	return nil
}

func writeGMLSerializePrimitive(b *strings.Builder, access string, f parser.Field, indent string) error {
	if f.Quant != nil {
		return writeGMLSerializeQuant(b, access, f, indent)
	}

	switch f.Primitive {
	case parser.KindFloat32:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_f32, %s);\n", indent, access)
	case parser.KindFloat64:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_f64, %s);\n", indent, access)
	case parser.KindInt8:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_s8, %s);\n", indent, access)
	case parser.KindUint8:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u8, %s);\n", indent, access)
	case parser.KindBool:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u8, %s ? 1 : 0);\n", indent, access)
	case parser.KindInt16:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_s16, %s);\n", indent, access)
	case parser.KindUint16:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u16, %s);\n", indent, access)
	case parser.KindInt32:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_s32, %s);\n", indent, access)
	case parser.KindUint32:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u32, %s);\n", indent, access)
	case parser.KindInt64:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_s64, %s);\n", indent, access)
	case parser.KindUint64:
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u64, %s);\n", indent, access)
	case parser.KindString:
		lenVar := "_slen_" + gmlVarSuffix(access)
		checkedVar := "_slen_checked_" + gmlVarSuffix(access)
		fmt.Fprintf(b, "%svar %s = string_byte_length(%s);\n", indent, lenVar, access)
		fmt.Fprintf(b, "%svar %s = arpack_ensure_u16_length(%s, %q);\n", indent, checkedVar, lenVar, lengthContext(f))
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u16, %s);\n", indent, checkedVar)
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_text, %s);\n", indent, access)
	}
	return nil
}

func writeGMLSerializeQuant(b *strings.Builder, access string, f parser.Field, indent string) error {
	q := f.Quant
	varName := "_q_" + gmlVarSuffix(access)
	fmt.Fprintf(b, "%sarpack_ensure_quant_range(%s, %g, %g, %q);\n",
		indent, access, q.Min, q.Max, quantContext(f))
	fmt.Fprintf(b, "%svar %s = %s;\n", indent, varName, quantizeExpr("gml", access, q, q.Bits))
	if q.Bits == 8 {
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u8, %s);\n", indent, varName)
	} else {
		fmt.Fprintf(b, "%sbuffer_write(_buf, buffer_u16, %s);\n", indent, varName)
	}
	return nil
}

func writeGMLDeserializeField(b *strings.Builder, recv string, f parser.Field, indent string) error {
	access := gmlFieldAccess(recv, f.Name)
	switch f.Kind {
	case parser.KindPrimitive:
		return writeGMLDeserializePrimitive(b, access, f, indent)
	case parser.KindNested:
		fmt.Fprintf(b, "%s%s = %s.deserialize(_buf)[0];\n", indent, access, f.TypeName)
	case parser.KindFixedArray:
		iVar := gmlLoopVar(f)
		fmt.Fprintf(b, "%s%s = array_create(%d);\n", indent, access, f.FixedLen)
		fmt.Fprintf(b, "%sfor (var %s = 0; %s < %d; %s++)\n", indent, iVar, iVar, f.FixedLen, iVar)
		fmt.Fprintf(b, "%s{\n", indent)
		elemField := *f.Elem
		elemField.Name = f.Name + "[" + iVar + "]"
		if err := writeGMLDeserializeField(b, recv, elemField, indent+"    "); err != nil {
			return err
		}
		fmt.Fprintf(b, "%s}\n", indent)
	case parser.KindSlice:
		lenVar := gmlLenVar(f)
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 2, %q);\n", indent, "slice length for "+f.Name)
		fmt.Fprintf(b, "%svar %s = buffer_read(_buf, buffer_u16);\n", indent, lenVar)
		fmt.Fprintf(b, "%s%s = array_create(%s);\n", indent, access, lenVar)
		iVar := gmlLoopVar(f)
		fmt.Fprintf(b, "%sfor (var %s = 0; %s < %s; %s++)\n", indent, iVar, iVar, lenVar, iVar)
		fmt.Fprintf(b, "%s{\n", indent)
		elemField := *f.Elem
		elemField.Name = f.Name + "[" + iVar + "]"
		if err := writeGMLDeserializeField(b, recv, elemField, indent+"    "); err != nil {
			return err
		}
		fmt.Fprintf(b, "%s}\n", indent)
	}
	return nil
}

func writeGMLDeserializePrimitive(b *strings.Builder, access string, f parser.Field, indent string) error {
	if f.Quant != nil {
		return writeGMLDeserializeQuant(b, access, f, indent)
	}

	switch f.Primitive {
	case parser.KindFloat32:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 4, %q);\n", indent, "float32")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_f32);\n", indent, access)
	case parser.KindFloat64:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 8, %q);\n", indent, "float64")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_f64);\n", indent, access)
	case parser.KindInt8:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 1, %q);\n", indent, "int8")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_s8);\n", indent, access)
	case parser.KindUint8:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 1, %q);\n", indent, "uint8")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_u8);\n", indent, access)
	case parser.KindBool:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 1, %q);\n", indent, "bool")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_u8) != 0;\n", indent, access)
	case parser.KindInt16:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 2, %q);\n", indent, "int16")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_s16);\n", indent, access)
	case parser.KindUint16:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 2, %q);\n", indent, "uint16")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_u16);\n", indent, access)
	case parser.KindInt32:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 4, %q);\n", indent, "int32")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_s32);\n", indent, access)
	case parser.KindUint32:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 4, %q);\n", indent, "uint32")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_u32);\n", indent, access)
	case parser.KindInt64:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 8, %q);\n", indent, "int64")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_s64);\n", indent, access)
	case parser.KindUint64:
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 8, %q);\n", indent, "uint64")
		fmt.Fprintf(b, "%s%s = buffer_read(_buf, buffer_u64);\n", indent, access)
	case parser.KindString:
		lenVar := "_slen_" + gmlVarSuffix(access)
		iVar := "_si_" + gmlVarSuffix(access)
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 2, %q);\n", indent, "string length for "+f.Name)
		fmt.Fprintf(b, "%svar %s = buffer_read(_buf, buffer_u16);\n", indent, lenVar)
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, %s, %q);\n", indent, lenVar, "string data for "+f.Name)
		fmt.Fprintf(b, "%svar _s = \"\";\n", indent)
		fmt.Fprintf(b, "%sfor (var %s = 0; %s < %s; %s++)\n", indent, iVar, iVar, lenVar, iVar)
		fmt.Fprintf(b, "%s{\n", indent)
		fmt.Fprintf(b, "%s    _s += chr(buffer_read(_buf, buffer_u8));\n", indent)
		fmt.Fprintf(b, "%s}\n", indent)
		fmt.Fprintf(b, "%s%s = _s;\n", indent, access)
	}
	return nil
}

func writeGMLDeserializeQuant(b *strings.Builder, access string, f parser.Field, indent string) error {
	q := f.Quant
	varName := "_q_" + gmlVarSuffix(access)
	if q.Bits == 8 {
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 1, %q);\n", indent, "quantized value for "+f.Name)
		fmt.Fprintf(b, "%svar %s = buffer_read(_buf, buffer_u8);\n", indent, varName)
	} else {
		fmt.Fprintf(b, "%sarpack_ensure_readable(_buf, 2, %q);\n", indent, "quantized value for "+f.Name)
		fmt.Fprintf(b, "%svar %s = buffer_read(_buf, buffer_u16);\n", indent, varName)
	}
	expr := dequantizeExpr("gml", varName, q, f.Primitive)
	fmt.Fprintf(b, "%s%s = %s;\n", indent, access, expr)
	return nil
}

func gmlFieldName(name string) string {
	return ToSnakeCase(name)
}

func gmlFieldAccess(recv, name string) string {
	suffix := ""
	base := name
	if idx := strings.IndexByte(name, '['); idx >= 0 {
		base = name[:idx]
		suffix = name[idx:]
	}

	fieldName := gmlFieldName(base)
	if isLuaIdentifier(fieldName) && !isGMLKeyword(fieldName) {
		return recv + "." + fieldName + suffix
	}
	return fmt.Sprintf("%s[%q]%s", recv, fieldName, suffix)
}

func gmlVarSuffix(s string) string {
	return strings.TrimLeft(strings.ToLower(sanitizeVarName(s)), "_")
}

func gmlLoopVar(f parser.Field) string {
	return "_i" + gmlVarSuffix(f.Name)
}

func gmlLenVar(f parser.Field) string {
	return "_len" + gmlVarSuffix(f.Name)
}

func gmlIsEnumType(f parser.Field, enumNames map[string]struct{}) bool {
	if f.NamedType == "" || enumNames == nil {
		return false
	}
	_, ok := enumNames[f.NamedType]
	return ok
}

func gmlDefaultValue(f parser.Field, enumNames map[string]struct{}) string {
	switch f.Kind {
	case parser.KindPrimitive:
		if gmlIsEnumType(f, enumNames) {
			return "0"
		}
		switch f.Primitive {
		case parser.KindString:
			return `""`
		case parser.KindBool:
			return "false"
		default:
			return "0"
		}
	case parser.KindNested:
		return "new " + f.TypeName + "()"
	case parser.KindFixedArray, parser.KindSlice:
		return "array_create(0)"
	}
	return "0"
}

func gmlDefaultNeedsFactory(f parser.Field) bool {
	switch f.Kind {
	case parser.KindPrimitive:
		return false
	case parser.KindNested, parser.KindFixedArray, parser.KindSlice:
		return true
	}
	return true
}

func isGMLKeyword(s string) bool {
	switch s {
	case "begin", "break", "case", "constructor", "continue", "default", "delete", "div",
		"do", "else", "elseif", "end", "endif", "endswitch", "enum", "exit", "false", "for",
		"function", "global", "globalvar", "if", "in", "inherited", "localvar", "mod", "new",
		"noone", "not", "or", "other", "out", "repeat", "return", "self", "static", "struct",
		"switch", "then", "throw", "true", "try", "until", "var", "while", "with", "xor",
		"all", "undefined":
		return true
	}
	return false
}
