version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gocritic
    - misspell
    - prealloc
    - unconvert
    - unparam

formatters:
  enable:
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/edmand46/arpack