FROM golang:1.21-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    protobuf-compiler \
    flatbuffers-compiler \
    && rm -rf /var/lib/apt/lists/*

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11

WORKDIR /workspace
